apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
spec:
  template:
    spec:
      containers:
      - name: recommendations
        env:
        - name: WORKER_POOL_SIZE
          value: "8"