apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: "64Mi"
        env:
        - name: AUTH_JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: jwtPublicKey