apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
spec:
  template:
    spec:
      containers:
      - name: public-api
        env:
        - name: CONNECTION_POOL_SIZE
          value: "100"